In [46]:
import numpy as np

In [47]:
np.__version__
# 패키지의 버전 확인. '__'-> 내장변수

'1.19.5'

In [48]:
def onehotcylinder(cylinders):
  if cylinders == 3:
    cylinder = np.array([1,0,0,0,0])
  elif cylinders == 4:
    cylinder = np.array([0,1,0,0,0])
  elif cylinders == 5:
    cylinder = np.array([0,0,1,0,0])
  elif cylinders == 6:
    cylinder = np.array([0,0,0,1,0])
  else : # 8
    cylinder = np.array([0,0,0,0,1])  
  return cylinder

In [49]:
onehotcylinder(4), onehotcylinder(6)

(array([0, 1, 0, 0, 0]), array([0, 0, 0, 1, 0]))

In [50]:
displacement= 307.0
horsepower= 130.0
weight= 3504.0
accel= 12.0
cylinders = 8
origin = 1

# cylinder= 8, org= 1 -> onehot encoding

x_continus= np.array([displacement, horsepower, weight, accel])
cylinder= onehotcylinder(cylinders) # cylinder = np.array([0,0,0,0,1]) 
org= np.array([1,0,0])

In [51]:
type(x_continus)

numpy.ndarray

In [52]:
# np.concatenate((a, b), axis=None) 이어 붙이기
result= np.concatenate((x_continus, cylinder, org), axis=None)
result.shape, result # 12행

((12,),
 array([3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]))

In [53]:
# result.reshape(1, 12) # hard coding (행 수, 열 수)
result= result.reshape(-1, result.size) # soft coding 컬럼의 수가 바뀔 수 있음 
result, result.shape

(array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]]),
 (1, 12))

### function 이해

In [54]:
def sum():
  first= 21
  second= 14
  result= first + second
  return result

In [55]:
sum()

35

In [56]:
def sum(f1, s2):
  first= f1 
  second= s2
  result= first + second
  return result

In [57]:
# def differenceVars(*var1, **args2):
def diffparam(*var_list, **var_dict):
  print(var_dict)
  result1= len(var_list)
  return result1

In [58]:
diffparam(1, 2, 3, a=2, b=3) # 키 없는 값은 알아서 리스트

{'a': 2, 'b': 3}


3

In [59]:
diffparam(1, 2, 3, 4, 5, c=5, d=6, a=2,b=3)

{'c': 5, 'd': 6, 'a': 2, 'b': 3}


5