 ## class sklearn.model_selection.KFold(n_splits=5, *, shuffle=False, random_state=None)

In [4]:
import numpy as np
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [5, 6], [7, 8], [9, 0]])
y = np.array([1, 2, 3, 4, 2, 3, 1])
X.shape, y.shape

((7, 2), (7,))

In [10]:
from sklearn.model_selection import KFold
kf = KFold(n_splits= 3, shuffle= True)
kf.get_n_splits(X)

3

In [12]:
for first, second in kf.split(X):
  print(first, ' : ', second)
  # 데이터를 n번 나눈다
  # X 배열의 인덱스 값을 나타냄
  # [ train용 ] : [ test용 ]

[3 4 5 6]  :  [0 1 2]
[0 1 2 3 6]  :  [4 5]
[0 1 2 4 5]  :  [3 6]


In [15]:
type(first), type(second), first.shape, second.shape

(numpy.ndarray, numpy.ndarray, (5,), (2,))

In [18]:
for first, second in kf.split(X):
  print(first, ' : ', second)
  x_train= X[first]
  print(x_train)
  x_test= X[second]
  print(x_test)
  # 첫줄: 인덱스 값 
  # 나머지 줄: 인덱스 위치에 있는 값

[0 1 4 5]  :  [2 3 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [9 0]]
[1 2 3 4 6]  :  [0 5]
[[3 4]
 [1 2]
 [3 4]
 [5 6]
 [9 0]]
[[1 2]
 [7 8]]
[0 2 3 5 6]  :  [1 4]
[[1 2]
 [1 2]
 [3 4]
 [7 8]
 [9 0]]
[[3 4]
 [5 6]]
